name: 📖 文档改进
description: 报告文档问题或建议改进
title: "[Docs] "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你帮助改进文档！好的文档对新手贡献者非常重要。

  - type: input
    id: title
    attributes:
      label: 问题标题
      description: 简洁描述文档问题
      placeholder: 例如：README.md中的安装步骤不完整
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: 问题类型
      description: 这是什么类型的文档问题？
      options:
        - 错误信息 - 文档内容有误
        - 信息缺失 - 缺少重要信息
        - 表达不清 - 说明不够清楚
        - 格式问题 - 排版或格式有问题
        - 过时内容 - 信息已经过时
        - 语言问题 - 语法或用词问题
        - 新增建议 - 建议添加新内容
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: 文档位置
      description: 问题出现在哪个文件或页面？
      placeholder: 例如：README.md 第25-30行，或 docs/installation.md
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: 当前内容
      description: 复制有问题的现有内容（如果适用）
      render: markdown

  - type: textarea
    id: problem
    attributes:
      label: 问题描述
      description: 详细描述文档中存在什么问题
      placeholder: |
        例如：
        - 安装步骤没有说明Node.js版本要求
        - 新手可能会使用不兼容的版本导致失败
        - 缺少常见错误的解决方案
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: 改进建议
      description: 你建议如何修改或改进？
      placeholder: |
        例如：
        在安装步骤前添加：
        "注意：本项目需要Node.js 14.0.0或更高版本"
        并提供版本检查命令和升级指导
    validations:
      required: true

  - type: dropdown
    id: audience
    attributes:
      label: 目标读者
      description: 这个文档问题主要影响哪类用户？
      options:
        - 完全新手 - 第一次接触的用户
        - 初级用户 - 有基础但经验不多
        - 中级用户 - 有一定经验的用户
        - 高级用户 - 经验丰富的用户
        - 所有用户

  - type: textarea
    id: context
    attributes:
      label: 使用场景
      description: 在什么情况下遇到这个文档问题？
      placeholder: |
        例如：
        - 按照README安装时遇到困难
        - 寻找某个功能的使用方法时找不到
        - 想要贡献代码但不知道流程

  - type: textarea
    id: references
    attributes:
      label: 参考资料
      description: 有没有相关的资料或其他项目的好例子？
      placeholder: |
        例如：
        - 某某项目的文档写得很清楚
        - 相关的官方文档链接
        - 有用的教程或博客文章

  - type: checkboxes
    id: terms
    attributes:
      label: 确认项目
      options:
        - label: 我已经阅读了相关的现有文档
          required: true
        - label: 我已经搜索过是否有类似的文档改进建议
          required: true
        - label: 我的建议有助于改善用户体验
          required: true